name-template: 'v$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
categories:
  - title: 'ğŸš€ Features'
    labels:
      - 'enhancement'
  - title: 'ğŸ› Bug fixes'
    labels:
      - 'bug'
  - title: 'ğŸ§° Maintenance'
    labels:
      - 'chore'
      - 'refactor'
exclude-labels:
  - 'test'
  - 'documentation'
  - 'ci'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - 'semver:major'
  minor:
    labels:
      - 'semver:minor'
      - 'enhancement'
  patch:
    labels:
      - 'semver:patch'
      - 'bug'
      - 'refactor'
  default: patch
template: |
  ## Changes within @hivemq/ui-theme ğŸ¨

  $CHANGES

  ## Contributors

  Thanks to $CONTRIBUTORS for your contributions to this release!
